language: go

go:
  - "1.10"

script:
  - go test ./...

notifications:
  email: false


deploy:
  provider: script
  script: yarn global add now && now --public --token=$NOW_TOKEN
  on:
    branch: now_deploy