language: go

go:
  - "1.10"

script:
  - go test ./...

notifications:
  email: false

deploy:
  provider: cloudfoundry
  username: apikey
  password: $CLOUD_API_KEY
  api: https://api.ng.bluemix.net
  organization: joshblack@us.ibm.com
  space: keep-up