version: '3'
services:
  postgres:
    image: postgres:9.6.1
    ports:
    - "${DB_PORT:-5432}:5432"

    volumes:
    - "local-db-volume:/var/lib.postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keep_up_dev
volumes:
  local-db-volume:
    driver: local
