# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  test-go:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...

  deploy-graphql:
    docker:
      - image: kpup/deploy:v0.2
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      - run:
          name: Deploy to CloudFoundry
          command: cd graphql && bx cf push

  deploy-proxy:
    docker:
      - image: kpup/deploy:v0.2
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      - run:
          name: Deploy to CloudFoundry
          command: cd proxy && bx cf push

workflows:
  version: 2
  graphql:
    jobs:
      - test-go
      - deploy-graphql:
          requires:
            - test-go
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci

  proxy:
    jobs:
      - deploy-proxy:
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci
