# CircleCI 2.0 configuration file
version: 2
jobs:
  test-graphql:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...
  test-ui:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
            export PATH=$HOME/.yarn/bin:$PATH
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run CI Check
          command: yarn ci-check
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and publish Docker images
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            yarn install
            yarn workspaces run build
            echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin

            TAG="latest"
            if [ "${CIRCLE_TAG}" != "" ]; then
              TAG="${CIRCLE_TAG}"
            fi

            DOCKER_IMAGE_PROXY="keepupcompany/proxy:$TAG"
            DOCKER_IMAGE_GRAPHQL="keepupcompany/graphql:$TAG"

            docker build -t "$DOCKER_IMAGE_PROXY" --build-arg SITE='keepup.company' ./proxy
            docker build -t "$DOCKER_IMAGE_GRAPHQL" ./graphql

            docker push "$DOCKER_IMAGE_PROXY"
            docker push "$DOCKER_IMAGE_GRAPHQL"

      # - run:
          # name: deploy staging to IBM Cloud
          # command: |
            # Install `ibmcloud` CLI
            # curl -fsSL https://clis.ng.bluemix.net/install/linux | sh
            # # Login and push staging manifest
            # ibmcloud login \
              # --apikey $CLOUD_API_KEY \
              # -a https://api.ng.bluemix.net \
              # -o carbon-design-system \
              # -s production

            # ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
            # ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

            # ibmcloud cf blue-green-deploy carbon-website-staging \
              # -f .circleci/manifest.staging.yml \
              # --delete-old-apps
workflows:
  version: 2
  latest:
    jobs:
      # - test-graphql
      # - test-ui
      - deploy
      # - deploy:
          # requires:
            # - test-graphql
            # - test-ui
          # filters:
            # branches:
              # only: master
