# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  test-graphql:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...

  test-ui:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run CI Check
          command: yarn ci-check

  build-ui:
    requires:
      - test-ui
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Build
          command: cd ui && yarn build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ui/build/*

  deploy-graphql:
    docker:
      - image: kpup/deploy:v0.2
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      - run:
          name: Deploy to CloudFoundry
          command: cd graphql && bx cf push

  deploy-proxy:
    docker:
      - image: kpup/deploy:v0.2
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      - run:
          name: Deploy to CloudFoundry
          command: cd proxy && bx cf push

  deploy-ui:
    docker:
      - image: kpup/deploy:v0.2
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      - run:
          name: Copy build files
          command: cp -R /tmp/workspace/build ui/build
      - run:
          name: Output
          command: ls -al ui
      # - run:
          # name: Deploy to CloudFoundry
          # command: cd ui && bx cf push

workflows:
  version: 2
  graphql:
    jobs:
      - test-graphql
      - deploy-graphql:
          requires:
            - test-graphql
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci

  ui:
    jobs:
      - test-ui
      - deploy-ui:
          requires:
            - test-ui
            - build-ui
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci

  proxy:
    jobs:
      - deploy-proxy:
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci
