# CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/golang:1.10
      - image: circleci/node:9
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run: ls -al && pwd
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run unit tests
          command: go test -v ./...

  # test-graphql:
    # docker:
      # - image: circleci/golang:1.10
    # working_directory: /go/src/github.com/abbeyhrt/keep-up
    # steps:
      # - checkout
      # - run:
          # name: Run unit tests
          # command: go test -v ./...

  # test-ui:
    # docker:
      # - image: circleci/node:9
    # steps:
      # - checkout
      # - run:
          # name: Install dependencies
          # command: yarn
      # - run:
          # name: Run CI Check
          # command: yarn ci-check

  # build-ui:
    # docker:
      # - image: circleci/node:9
    # steps:
      # - checkout
      # - run:
          # name: Install dependencies
          # command: yarn
      # - run:
          # name: Make workspace directory
          # command: mkdir workspace && ls -al
      # - run:
          # name: Run build
          # command: cd ui && yarn build && cp -R build ../workspace/build
      # - persist_to_workspace:
          # root: workspace
          # paths:
            # - build

  # deploy-graphql:
    # docker:
      # - image: kpup/deploy:v0.2
    # working_directory: /go/src/github.com/abbeyhrt/keep-up
    # steps:
      # - checkout
      # - run:
          # name: Login to bx tool
          # command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      # - run:
          # name: Deploy to CloudFoundry
          # command: cd graphql && bx cf push

  # deploy-proxy:
    # docker:
      # - image: kpup/deploy:v0.2
    # working_directory: /go/src/github.com/abbeyhrt/keep-up
    # steps:
      # - checkout
      # - run:
          # name: Login to bx tool
          # command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      # - run:
          # name: Deploy to CloudFoundry
          # command: cd proxy && bx cf push

  # deploy-ui:
    # docker:
      # - image: kpup/deploy:v0.2
    # working_directory: /go/src/github.com/abbeyhrt/keep-up
    # steps:
      # - checkout
      # - attach_workspace:
          # at: workspace
      # - run:
          # name: Login to bx tool
          # command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net
      # - run:
          # name: Copy build files
          # command: cp -R workspace/build ui/build
      # - run:
          # name: Deploy to CloudFoundry
          # command: cd ui && bx cf push

# workflows:
  # version: 2

  # graphql:
    # jobs:
      # - deploy-graphql:
          # requires:
            # - test-graphql
          # filters:
            # branches:
              # # TODO: change to `master`
              # only: ci/update-circle-ci

  # ui:
    # jobs:
      # - build-ui:
          # requires:
            # - test-ui
          # filters:
            # branches:
              # # TODO: change to `master`
              # only: ci/update-circle-ci
      # - deploy-ui:
          # requires:
            # - test-ui
            # - build-ui
          # filters:
            # branches:
              # # TODO: change to `master`
              # only: ci/update-circle-ci

  # proxy:
    # jobs:
      # - deploy-proxy:
          # filters:
            # branches:
              # # TODO: change to `master`
              # only: ci/update-circle-ci
