# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  test-go:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...

  deploy-graphql:
    docker:
      - image: alpine:latest
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - run:
          name: Setup alpine dependencies
          command: |
            apk add --update unzip curl openssl ca-certificates git
            libc6-compat bash
            rm -rf /var/cache/apk/*
      - checkout
      - run: ls -al

workflows:
  version: 2
  graphql:
    jobs:
      - test-go
      - deploy-graphql:
          requires:
            - test
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci
