# CircleCI 2.0 configuration file
version: 2
jobs:
  test-graphql:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...
  test-ui:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
            export PATH=$HOME/.yarn/bin:$PATH
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run CI Check
          command: yarn ci-check
workflows:
  version: 2
  graphql:
    jobs:
      - test-graphql
  ui:
    jobs:
      - test-ui
