# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  test-go:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...

  deploy-graphql:
    docker:
      - image: alpine:latest
    working_directory: /go/src/github.com/abbeyhrt/keep-up
    steps:
      - run:
          name: Setup alpine dependencies
          command: |
            apk add --update unzip curl openssh openssl ca-certificates git bash
            rm -rf /var/cache/apk/*
            mkdir -p /tmp/bx
            curl -L -o /tmp/bx/cli https://clis.ng.bluemix.net/download/bluemix-cli/0.6.6/linux64
            tar -xf /tmp/bx/cli -C /tmp/bx
            chmod +x /tmp/bx/Bluemix_CLI/install_bluemix_cli
            bash /tmp/bx/Bluemix_CLI/install_bluemix_cli
            bx --help

      - checkout
      - run:
          name: Login to bx tool
          command: bx login --apikey $CLOUD_API_KEY -o $CLOUD_ORG -s $CLOUD_SPACE -a https://api.ng.bluemix.net

      - run: bx cf o

workflows:
  version: 2
  graphql:
    jobs:
      - test-go
      - deploy-graphql:
          requires:
            - test-go
          filters:
            branches:
              # TODO: change to `master`
              only: ci/update-circle-ci
