language: node_js

node_js:
  - '9'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn ci-check

before_deploy:
  - yarn build

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: apikey
  password: $CLOUD_API_KEY
  api: https://api.ng.bluemix.net
  organization: joshblack@us.ibm.com
  space: dev
  on:
    branch: master
